import dynamic from 'next/dynamic'
import Container from 'react-bootstrap/Container'
import Row from 'react-bootstrap/Row'
import Col from 'react-bootstrap/Col'

const DynamicBelowTheFold = dynamic(() => import('@/components/Privacy/BelowTheFold'))

function Privacy() {
  return (
    <Container fluid='xxl' className='Privacy'>
      <Row>
        <Col md={{ span: 6, offset: 3 }}>
          <p>
            Disclaimer: The opinions expressed herein are my own personal opinions and do not
            represent my employer’s view in any way.
          </p>

          <h1>Privacy Policy</h1>

          <p>Effective date: May 29, 2021</p>

          <p>
            Benjamin Brooke&apos;s Web Development Blog (&quot;us&quot;, &quot;we&quot;, or
            &quot;our&quot;) operates the https://bvgsoftware.com website (the &quot;Service&quot;).
          </p>

          <p>
            This page informs you of our policies regarding the collection, use, and disclosure of
            personal data when you use our Service and the choices you have associated with that
            data.
          </p>

          <p>
            We use your data to provide and improve the Service. By using the Service, you agree to
            the collection and use of information in accordance with this policy. Unless otherwise
            defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings
            as in our Terms and Conditions, accessible from https://bvgsoftware.com/blog
          </p>

          <h2>Definitions</h2>
          <ul>
            <li>
              <p>
                <strong>Service</strong>
              </p>
              <p>
                Service is the https://bvgsoftware.com/blog website operated by Benjamin Brooke, an
                Individual.
              </p>
            </li>
            <li>
              <p>
                <strong>Personal Data</strong>
              </p>
              <p>
                Personal Data means data about a living individual who can be identified from those
                data (or from those and other information either in our possession or likely to come
                into our possession).
              </p>
            </li>
            <li>
              <p>
                <strong>Usage Data</strong>
              </p>
              <p>
                Usage Data is data collected automatically either generated by the use of the
                Service or from the Service infrastructure itself (for example, the duration of a
                page visit).
              </p>
            </li>
            <li>
              <p>
                <strong>Cookies</strong>
              </p>
              <p>
                Cookies are small pieces of data stored on your device (computer or mobile device).
              </p>
            </li>
            <li>
              <p>
                <strong>Data Controller</strong>
              </p>
              <p>
                Data Controller means the natural or legal person who (either alone or jointly or in
                common with other persons) determines the purposes for which and the manner in which
                any personal information are, or are to be, processed.
              </p>
              <p>
                For the purpose of this Privacy Policy, we are a Data Controller of your Personal
                Data.
              </p>
            </li>
            <li>
              <p>
                <strong>Data Processors (or Service Providers)</strong>
              </p>
              <p>
                Data Processor (or Service Provider) means any natural or legal person who processes
                the data on behalf of the Data Controller.
              </p>
              <p>
                We may use the services of various Service Providers in order to process your data
                more effectively.
              </p>
            </li>
            <li>
              <p>
                <strong>Data Subject (or User)</strong>
              </p>
              <p>
                Data Subject is any living individual who is using our Service and is the subject of
                Personal Data.
              </p>
            </li>
          </ul>
          <DynamicBelowTheFold />
        </Col>
      </Row>
    </Container>
  )
}

export default Privacy
