export default {
  '/': 'Home',
  blog: 'Blog',
  courses: 'Courses',
  about: 'About',
  privacy: 'Privacy Policy',
  'frequently-asked-questions': 'Frequently Asked Questions',
  'how-to-analyze-and-optimize-your-nextjs-production-build':
    'How To Analyze And Optimize A NextJS Build',
  'how-to-setup-nextjs-strapi-postgres-nginx-on-digital-ocean':
    'How To Setup NextJS & Strapi On Digital Ocean',
  'how-to-build-a-color-picker-with-react': 'Build a Color Picker',
  'react-svg-icons-with-no-artistic-abilities': 'SVG Without Artistic Ability',
  'save-development-time-with-autohotkey': 'How To Use AutoHotKey',
  'high-school-clock': 'High School Clock',
  'react-form-validation-with-formik-graphql-yup': 'React Forkmik Validation',
  'how-to-build-a-command-line-application-with-node': 'Build a CLI With Node',
  'read-time-feature-for-react-markdown-blog': 'Build a Read Time Feature',
  'how-to-use-local-storage-to-persist-data': 'How To Use Local Storage',
  'wordpress-form-to-email-and-google-sheet': 'WordPress Form To Email',
  'build-an-ecommerce-color-search-tool-with-nodejs-react-1': 'Build a Color Search Tool',
  'how-to-encode-gifs-with-node': 'Encode GIFs With Node',
  'react-contact-form-with-klaviyo-and-formik': 'Build a React Contact Form',
  'simple-binary-search-tree': 'Binary Search Tree',
  minesweeper: 'Minesweeper',
  'build-a-blog-article-progress-bar-with-react-and-bootstrap': 'Build a Progress Bar',
}
